#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define DW1000_CONF_RANGING_ENABLED 1

#include "deca_device_api.h"

#define APP_RADIO_CONF 1

#if APP_RADIO_CONF == 1
#define DW1000_CONF_CHANNEL        4
#define DW1000_CONF_PRF            DWT_PRF_16M
#define DW1000_CONF_PLEN           DWT_PLEN_128
#define DW1000_CONF_PAC            DWT_PAC8
#define DW1000_CONF_SFD_MODE       0
#define DW1000_CONF_DATA_RATE      DWT_BR_6M8
#define DW1000_CONF_PHR_MODE       DWT_PHRMODE_STD
#define DW1000_CONF_PREAMBLE_CODE  7
#define DW1000_CONF_SFD_TIMEOUT    (129 + 8 - 8)

#elif APP_RADIO_CONF == 2
#define DW1000_CONF_CHANNEL        2
#define DW1000_CONF_PRF            DWT_PRF_64M
#define DW1000_CONF_PLEN           DWT_PLEN_1024
#define DW1000_CONF_PAC            DWT_PAC32
#define DW1000_CONF_SFD_MODE       0
#define DW1000_CONF_DATA_RATE      DWT_BR_110K
#define DW1000_CONF_PHR_MODE       DWT_PHRMODE_STD
#define DW1000_CONF_PREAMBLE_CODE  9
#define DW1000_CONF_SFD_TIMEOUT    (1025 + 64 - 32)

#elif APP_RADIO_CONF == 3
#define DW1000_CONF_CHANNEL        4
#define DW1000_CONF_PRF            DWT_PRF_64M
#define DW1000_CONF_PLEN           DWT_PLEN_1024
#define DW1000_CONF_PAC            DWT_PAC8
#define DW1000_CONF_SFD_MODE       0
#define DW1000_CONF_DATA_RATE      DWT_BR_6M8
#define DW1000_CONF_PHR_MODE       DWT_PHRMODE_STD
#define DW1000_CONF_PREAMBLE_CODE  7
#define DW1000_CONF_SFD_TIMEOUT    (129 + 8 - 8)
#endif


#define NETSTACK_CONF_NETWORK    sicslowpan_driver
#define NETSTACK_CONF_MAC        nullmac_driver
#define NETSTACK_CONF_RDC        nullrdc_driver

#define NETSTACK_CONF_WITH_IPV6     1
#define UIP_CONF_ROUTER             1


#define DW1000_CONF_AUTOACK         0
#define DW1000_CONF_FRAMEFILTER     0
#define DW1000_CONF_RANGING_ENABLED 1
#define DW1000_CONF_READ_RXDIAG     1

#ifndef WITH_NON_STORING
#define WITH_NON_STORING 0
#endif

#undef NBR_TABLE_CONF_MAX_NEIGHBORS
#define NBR_TABLE_CONF_MAX_NEIGHBORS 5

#undef UIP_CONF_MAX_ROUTES
#define UIP_CONF_MAX_ROUTES   10

#define RANGING_DAO 1
#define RPL_CONF_DIO_REFRESH_DAO_ROUTES 1
#define RPL_CONF_PROBING_INTERVAL (15 * CLOCK_SECOND)
#define RPL_CONF_DAG_LIFETIME 1

#endif // PROJECT_CONF_H_
